Tensors 类似于 NumPy 的 ndarrays ，同时 Tensors 可以使用 GPU 进行计算。下面开始学习torch。

# PyTorch中的Tensors

## 构造Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# 验证安装
print(torch)

<module 'torch' from '/opt/anaconda3/envs/py37_torch/lib/python3.7/site-packages/torch/__init__.py'>


构造一个5x3矩阵，不初始化。 

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -2.5315e+22, -1.1931e-37],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -4.3902e+24,  3.5028e+22],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


构造一个随机初始化的矩阵：

In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6001, 0.5671, 0.9150],
        [0.1645, 0.7707, 0.9551],
        [0.0138, 0.6380, 0.1439],
        [0.4128, 0.9922, 0.4738],
        [0.5030, 0.3991, 0.0636]])


构造一个矩阵全为 0，而且数据类型是 long.

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


构造一个张量，直接使用数据：

In [6]:
x = torch.tensor([5.5, 3]) 
print(x)

tensor([5.5000, 3.0000])


创建一个 tensor 基于已经存在的 tensor。

In [7]:
x = x.new_ones(5, 3, dtype=torch.double) 
# new_* methods take in sizes 
print(x) 

x = torch.randn_like(x, dtype=torch.float) 
# override dtype! 
print(x) 
# result has the same size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.9959,  1.0573,  1.0797],
        [ 1.1140,  0.0838,  1.4446],
        [-1.3747, -1.8302,  0.0505],
        [-0.3879,  0.9535, -0.4932],
        [ 0.2444, -0.9269,  2.2756]])
torch.Size([5, 3])


>注意 torch.Size 是一个元组，所以它支持左右的元组操作。

## Tensors运算

加法

In [8]:
y = torch.rand(5,3)
# 加法: 方式 1
print(x + y)
# 加法: 方式 2
print(torch.add(x, y))
# 加法: 提供一个输出 tensor 作为参数
result = torch.empty(5, 3) 
torch.add(x, y, out=result) 
print(result)
# 加法: in-place  
# adds x to y 
y.add_(x) 
print(y)


tensor([[ 1.3746,  1.4511,  2.0600],
        [ 1.8730,  0.2984,  2.1123],
        [-0.6829, -1.4472,  0.8868],
        [ 0.5287,  1.0136, -0.0778],
        [ 1.1283, -0.8318,  2.7502]])
tensor([[ 1.3746,  1.4511,  2.0600],
        [ 1.8730,  0.2984,  2.1123],
        [-0.6829, -1.4472,  0.8868],
        [ 0.5287,  1.0136, -0.0778],
        [ 1.1283, -0.8318,  2.7502]])
tensor([[ 1.3746,  1.4511,  2.0600],
        [ 1.8730,  0.2984,  2.1123],
        [-0.6829, -1.4472,  0.8868],
        [ 0.5287,  1.0136, -0.0778],
        [ 1.1283, -0.8318,  2.7502]])
tensor([[ 1.3746,  1.4511,  2.0600],
        [ 1.8730,  0.2984,  2.1123],
        [-0.6829, -1.4472,  0.8868],
        [ 0.5287,  1.0136, -0.0778],
        [ 1.1283, -0.8318,  2.7502]])


>注意 任何使张量会发生变化的操作都有一个前缀 ‘’。例如：x.copy(y), x.t_(), 将会改变 x.

## Torch切片

可以使用标准的 NumPy 类似的索引操作

In [9]:
print(x[:,1])

tensor([ 1.0573,  0.0838, -1.8302,  0.9535, -0.9269])


In [10]:
x = torch.randn(4, 4) 
y = x.view(16) 
z = x.view(-1, 8) 
# the size -1 is inferred from other dimensions 
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有一个元素 tensor ，使用 .item() 来获得这个 value 。
>注：必須是單元素

In [13]:
x = torch.randn(1) 
print(x) 
print(x.item())

tensor([1.2333])
1.233268141746521
